### ISSUE TITLE
ranges_cleanup: [untemp] A better best design

### ISSUE THREAD

**Issue by JohelEGP** [CaseyCarter/papers#1]
I noticed a difference between the `void` specializations of the comparison function objects in `std` and those in `std::ranges`. The return type of the constrained ones are narrowed to `bool`, while the unconstrained ones preserve the return type. In that case, I'd like to suggest changing the constrained ones to preserve the return type too, which would make them more useful with the types taking advantage of `<=>` and consistent with their unconstrained counterparts.

**Comment by JohelEGP** [comment]
Ping @CaseyCarter. I noticed you aren't watching this repository. Fortunately, new repositories are automatically set as watched for their creator.

**Comment by CaseyCarter** [comment]
> In that case, I'd like to suggest changing the constrained ones to preserve the return type too, which would make them more useful with the types taking advantage of <=> and consistent with their unconstrained counterparts.

The inconsistency here is an intentional design feature: the constraints on the call operators of the `ranges` comparison function objects require the argument types to model `EqualityComparableWith` (`equal` and `not_equal`) or `StrictTotallyOrderedWith` (`less`, etc.) which require the return type of the comparison operators to model `Boolean` and therefore `ConvertibleTo<bool>`. 

What's the issue with `<=>`? `<=>` typically will return one of the comparison category types, which means that comparison expressions that are rewritten as spaceship expressions will have type `bool`.

**Comment by JohelEGP** [comment]
> [...] `<=>` typically will return one of the comparison category types, which means that comparison expressions that are rewritten as spaceship expressions will have type `bool`.

I thought that the rewrite preserved the return type of `<=>`. That led me to believe that the constrained comparison function objects lost the type information by fixing the return type to `bool`. Turns out there's nothing lost. Thank you.
